[server]
headless = true
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#22D3EE"
backgroundColor = "#061526"
secondaryBackgroundColor = "#0A2340"
textColor = "#F8FAFC"
